package io.github.edadma.trisc

class CommentTests extends TestHelpers {

  // ===== ; comments (discarded by lexer) =====

  "; comment on its own line is discarded" in {
    val cpu = runCPU(VECTORS + "; this is a comment\nldi r1, 42\nhalt\n")
    cpu.r(1).read shouldBe 42
  }

  "; inline comment after instruction is discarded" in {
    val cpu = runCPU(VECTORS + "ldi r1, 42 ; load 42\nhalt\n")
    cpu.r(1).read shouldBe 42
  }

  "; inline comment after label is discarded" in {
    val cpu = runCPU(VECTORS +
      """ldi r1, 42 ; set up value
        |bra done ; skip next
        |ldi r1, 0
        |done ; target label
        |  halt
        |""".stripMargin)
    cpu.r(1).read shouldBe 42
  }

  "; comment does not appear in TOF output" in {
    val tof = assemble(VECTORS + "; discarded comment\nldi r1, 42\nhalt\n")
    val s = tof.serialize
    s should not include "discarded comment"
  }

  "; multiple consecutive comments" in {
    val cpu = runCPU(VECTORS +
      """; comment 1
        |; comment 2
        |; comment 3
        |ldi r1, 99
        |halt
        |""".stripMargin)
    cpu.r(1).read shouldBe 99
  }

  // ===== # comments (preserved into TOF) =====

  "# comment on its own line is preserved in TOF" in {
    val tof = assemble(VECTORS + "# generated by compiler\nldi r1, 42\nhalt\n")
    val s = tof.serialize
    s should include("# generated by compiler")
  }

  "# comment round-trips through serialize/deserialize" in {
    val tof = assemble(VECTORS + "# function: main\nldi r1, 42\nhalt\n")
    val s = tof.serialize
    val tof2 = TOF.fromString(s)
    tof2.serialize shouldBe s
  }

  "# comment does not affect code execution" in {
    val cpu = runCPU(VECTORS + "# this is a preserved comment\nldi r1, 42\nhalt\n")
    cpu.r(1).read shouldBe 42
  }

  "multiple # comments preserved in order" in {
    val tof = assemble(VECTORS +
      """# file: test.c
        |# function: main
        |ldi r1, 42
        |# call helper
        |halt
        |""".stripMargin)
    val s = tof.serialize
    s should include("# file: test.c")
    s should include("# function: main")
    s should include("# call helper")
    // check order
    s.indexOf("file: test.c") should be < s.indexOf("function: main")
    s.indexOf("function: main") should be < s.indexOf("call helper")
  }

  "# comment with no space after #" in {
    val tof = assemble(VECTORS + "#no-space-comment\nldi r1, 42\nhalt\n")
    val s = tof.serialize
    s should include("# no-space-comment")
  }

  "# and ; comments can coexist" in {
    val tof = assemble(VECTORS +
      """# preserved comment
        |; discarded comment
        |ldi r1, 42 ; also discarded
        |# another preserved
        |halt
        |""".stripMargin)
    val s = tof.serialize
    s should include("# preserved comment")
    s should include("# another preserved")
    s should not include "discarded comment"
    s should not include "also discarded"
  }

  "# comments work in relocatable mode" in {
    val tof = assemble(
      """# module: main
        |global main, func
        |main
        |  # entry point
        |  ldi r1, 42
        |  halt
        |""".stripMargin, relocatable = true)
    val s = tof.serialize
    s should include("# module: main")
    s should include("# entry point")
    tof.symbolByName("main").get.typ shouldBe SymbolType.Func
  }

  // ===== # comments in TOF.fromString =====

  "TOF.fromString preserves # comments" in {
    val input = "TOF v2\nSEGMENT:code,0\n# hello world\nDATA:002a\n"
    val tof = TOF.fromString(input)
    val s = tof.serialize
    s should include("# hello world")
  }

  "TOF.fromString handles # comment at start of segment" in {
    val input = "TOF v2\nSEGMENT:code,0\n# first line\nDATA:00\n"
    val tof = TOF.fromString(input)
    tof.segments.head.chunks.head shouldBe a[TOF.CommentChunk]
  }

  "TOF.fromString handles # comment between data chunks" in {
    val input = "TOF v2\nSEGMENT:code,0\nDATA:01\n# middle\nDATA:02\n"
    val tof = TOF.fromString(input)
    tof.segments.head.chunks(1) shouldBe TOF.CommentChunk("middle")
  }

  // ===== # comments don't affect data =====

  "# comments don't affect data size" in {
    val tof = assemble(VECTORS + "# comment\nldi r1, 42\nhalt\n")
    tof.totalDataSize shouldBe assemble(VECTORS + "ldi r1, 42\nhalt\n").totalDataSize
  }

  "# comments don't affect load" in {
    val tof = assemble(VECTORS + "# comment\nldi r1, 42\nhalt\n")
    val ram = new RAM(0, 0x1000)
    tof.load(ram) // should not throw
  }
}
