package io.github.edadma.trisc

import io.github.edadma.toml.{TomlParser, TomlValue}
import TomlValue.*

/** SLIX build configuration.
  *
  * Reads a `sysl.toml` file and produces the text of a generated sysl config
  * module. The generated file is a plain `.sysl` source with `module <path>`
  * declaration (if specified) followed by `val NAME = literal` declarations
  * for every integer key in the configuration.
  *
  * The mapping from TOML keys to sysl val names is UPPER_SNAKE_CASE:
  * `max_threads = 8` becomes `val MAX_THREADS = 8`.
  *
  * Hex literals in TOML (`0x7FE000`) are emitted as hex in the generated
  * file to preserve intent.
  */
object SyslBuildConfig:

  final case class Error(msg: String) extends RuntimeException(msg)

  /** Result of loading a sysl.toml: the generated file path (relative to
    * repo root) and the generated file content.
    */
  final case class Generated(path: String, content: String)

  /** Parse a `sysl.toml` source string and produce the generated config
    * file path and content.
    */
  def generate(tomlSource: String): Generated =
    val doc = TomlParser.parse(tomlSource) match
      case Right(d)  => d
      case Left(msg) => throw Error(s"sysl.toml: parse error: $msg")

    val module = doc.getString("config.module")

    // Collect (name, value, formatHint) triples from every section
    // besides [target] and [config].
    val excludedSections = Set("target", "config")
    val groups = doc.root.toList.flatMap {
      case (name, _) if excludedSections.contains(name) => None
      case (name, Obj(values)) => Some(name -> extractInts(name, values))
      case (name, other) =>
        throw Error(s"sysl.toml: [$name] must be a table, got $other")
    }

    // Build the generated source.
    val sb = new StringBuilder
    sb ++= "// Generated by GenerateConfigMain from sysl.toml.\n"
    sb ++= "// DO NOT EDIT by hand — run the generator to regenerate.\n\n"

    module.foreach { m =>
      sb ++= s"module $m\n\n"
    }

    for (section, entries) <- groups if entries.nonEmpty do
      sb ++= s"// [$section]\n"
      val maxNameWidth = entries.map(_._1.length).max
      for (name, value, fmt) <- entries do
        val padded = name.padTo(maxNameWidth, ' ')
        sb ++= s"val $padded = ${formatValue(value, fmt)}\n"
      sb ++= "\n"

    val outputPath = module match
      case Some(m) =>
        val parts = m.split('.')
        if parts.isEmpty then "config.sysl"
        else parts.mkString("/") + "/" + parts.last + ".sysl"
      case None => "config.sysl"

    Generated(outputPath, sb.toString)

  private enum ValueFormat:
    case Decimal
    case Hex

  private def extractInts(section: String, values: scala.collection.immutable.VectorMap[String, TomlValue]): List[(String, Long, ValueFormat)] =
    values.toList.map {
      case (key, Num(n)) =>
        val name = key.toUpperCase
        val fmt = if n >= 0x10000 || n < 0 then ValueFormat.Hex else ValueFormat.Decimal
        (name, n, fmt)
      case (key, other) =>
        throw Error(s"sysl.toml: [$section].$key must be an integer, got $other")
    }

  private def formatValue(value: Long, fmt: ValueFormat): String =
    fmt match
      case ValueFormat.Decimal => value.toString
      case ValueFormat.Hex     => "0x" + value.toHexString.toUpperCase
