package io.github.edadma.trisc

import toml.Value

/** SLIX build configuration.
  *
  * Reads a `sysl.toml` file and produces the text of a generated sysl config
  * module. The generated file is a plain `.sysl` source with `module <path>`
  * declaration (if specified) followed by `val NAME = literal` declarations
  * for every integer key in the configuration.
  *
  * The mapping from TOML keys to sysl val names is UPPER_SNAKE_CASE:
  * `max_threads = 8` becomes `val MAX_THREADS = 8`.
  *
  * Hex literals in TOML (`0x7FE000`) are emitted as hex in the generated
  * file to preserve intent.
  */
object SyslBuildConfig:

  final case class Error(msg: String) extends RuntimeException(msg)

  /** Result of loading a sysl.toml: the generated file path (relative to
    * repo root) and the generated file content.
    */
  final case class Generated(path: String, content: String)

  /** Parse a `sysl.toml` source string and produce the generated config
    * file path and content.
    */
  def generate(tomlSource: String): Generated =
    val ast = toml.Toml.parse(tomlSource) match
      case Right(tbl: Value.Tbl) => tbl
      case Right(other)          => throw Error(s"sysl.toml: expected a table at the top level, got $other")
      case Left((addr, msg))     => throw Error(s"sysl.toml: parse error at $addr: $msg")

    // [config] section — optional; controls module name / output path.
    val configSection: Option[Map[String, Value]] = ast.values.get("config") match
      case Some(Value.Tbl(v)) => Some(v)
      case Some(other)        => throw Error(s"sysl.toml: [config] must be a table, got $other")
      case None               => None

    val module: Option[String] = configSection.flatMap(_.get("module")).map {
      case Value.Str(s) => s
      case other        => throw Error(s"sysl.toml: [config].module must be a string, got $other")
    }

    // Collect (name, value, formatHint) triples from every other section.
    // Sections besides [target] and [config] are treated as constant groups
    // and their integer keys become vals in the generated file.
    val excludedSections = Set("target", "config")
    val groups: List[(String, List[(String, Long, ValueFormat)])] =
      ast.values.toList.flatMap {
        case (name, _) if excludedSections.contains(name) => None
        case (name, Value.Tbl(values))                    => Some(name -> extractInts(name, values))
        case (name, other) =>
          throw Error(s"sysl.toml: [$name] must be a table, got $other")
      }

    // Build the generated source.
    val sb = new StringBuilder
    sb ++= "// Generated by GenerateConfigMain from sysl.toml.\n"
    sb ++= "// DO NOT EDIT by hand — run the generator to regenerate.\n\n"

    module.foreach { m =>
      sb ++= s"module $m\n\n"
    }

    for (section, entries) <- groups if entries.nonEmpty do
      sb ++= s"// [$section]\n"
      // Compute a column width so the `=` signs line up within each group.
      val maxNameWidth = entries.map(_._1.length).max
      for (name, value, fmt) <- entries do
        val padded = name.padTo(maxNameWidth, ' ')
        sb ++= s"val $padded = ${formatValue(value, fmt)}\n"
      sb ++= "\n"

    // Derive the output path. If module is e.g. "oskit.config", the file
    // goes at oskit/config/config.sysl. If no module, it goes at repo root
    // as config.sysl.
    val outputPath = module match
      case Some(m) =>
        val parts = m.split('.')
        if parts.isEmpty then "config.sysl"
        else parts.mkString("/") + "/" + parts.last + ".sysl"
      case None => "config.sysl"

    Generated(outputPath, sb.toString)

  private enum ValueFormat:
    case Decimal
    case Hex

  /** Extract integer keys from a TOML table, converting the key to
    * UPPER_SNAKE_CASE. Non-integer values are rejected.
    */
  private def extractInts(section: String, values: Map[String, Value]): List[(String, Long, ValueFormat)] =
    values.toList.map {
      case (key, Value.Num(n)) =>
        val name = key.toUpperCase
        // Use hex format for any value above 0xFFFF to preserve readability
        // for address-like constants.
        val fmt = if n >= 0x10000 || n < 0 then ValueFormat.Hex else ValueFormat.Decimal
        (name, n, fmt)
      case (key, other) =>
        throw Error(s"sysl.toml: [$section].$key must be an integer, got $other")
    }

  private def formatValue(value: Long, fmt: ValueFormat): String =
    fmt match
      case ValueFormat.Decimal => value.toString
      case ValueFormat.Hex     => "0x" + value.toHexString.toUpperCase
