package io.github.edadma.trisc

import org.scalatest.freespec.AnyFreeSpec
import org.scalatest.matchers.should.Matchers
import java.nio.file.{Files, Path}
import scala.sys.process.*

/** Snapshot tests for the diagnostic surface added in chunk 6: lock-version
 *  compatibility, --locked / --frozen mismatch, richer git-conflict context,
 *  and the `sysl tree` print format.
 *
 *  Hermetic by construction: every test stages its inputs under
 *  `target/sysl_test_diag/` and (where git is involved) installs an isolated
 *  `JvmGitFetcher` against a fresh per-test cache root. */
class SyslCliDiagnosticsTests extends AnyFreeSpec with Matchers {

  FileOps.instance = JvmFileOps

  private def runCli(args: String*): (Int, String) = CliCapture.runCli(args)

  private val stagingCounter = new java.util.concurrent.atomic.AtomicInteger(0)

  private def stagingDir(label: String): (Path, String) =
    val baseRel = "target/sysl_test_diag"
    val baseAbs = java.nio.file.Paths.get(baseRel).toAbsolutePath
    Files.createDirectories(baseAbs)
    val unique = stagingCounter.incrementAndGet()
    val abs = baseAbs.resolve(s"${label}_$unique")
    if Files.exists(abs) then deleteRecursive(abs)
    Files.createDirectories(abs)
    val rel = s"$baseRel/${label}_$unique"
    (abs, rel)

  private def deleteRecursive(p: Path): Unit =
    if Files.isDirectory(p) then
      val it = Files.list(p)
      try it.forEach(child => deleteRecursive(child))
      finally it.close()
    Files.deleteIfExists(p)

  private def writeFile(dir: Path, rel: String, contents: String): Path =
    val p = dir.resolve(rel)
    Files.createDirectories(p.getParent)
    Files.writeString(p, contents)
    p

  private def git(cwd: Path, args: String*): String =
    val out = new StringBuilder
    val err = new StringBuilder
    val log = ProcessLogger(line => out.append(line).append('\n'),
                            line => err.append(line).append('\n'))
    val rc = Process(Seq("git") ++ args, cwd.toFile).!(log)
    if rc != 0 then
      throw new RuntimeException(
        s"git ${args.mkString(" ")} (in $cwd) failed: ${err.toString.trim}")
    out.toString.trim

  private def makeFixtureRepo(dir: Path, files: Map[String, String]): (String, String) =
    Files.createDirectories(dir)
    git(dir, "init", "--quiet", "--initial-branch=main")
    git(dir, "config", "user.email", "test@example.invalid")
    git(dir, "config", "user.name", "Test")
    for (rel, contents) <- files do
      val f = dir.resolve(rel)
      Files.createDirectories(f.getParent)
      Files.writeString(f, contents)
      git(dir, "add", rel)
    git(dir, "commit", "--quiet", "-m", "fixture commit")
    val sha = git(dir, "rev-parse", "HEAD")
    val url = "file://" + dir.toAbsolutePath.toString
    (sha, url)

  private def libFixture(repoDir: Path, pkgName: String, version: String, answer: Int): (String, String) =
    makeFixtureRepo(repoDir, Map(
      "sysl.toml" ->
        s"""[package]
           |name = "$pkgName"
           |version = "$version"
           |""".stripMargin,
      "lib/lib.lsysl" ->
        s"""    module lib
           |
           |    answer() -> int = $answer
           |""".stripMargin,
    ))

  private def withFetcher[A](label: String)(body: (Path, JvmGitFetcher) => A): A =
    // Hold CliCapture.ioLock for the whole body so other suites' tests can't
    // overwrite GitFetcherProvider.instance between two of our runCli calls.
    CliCapture.ioLock.synchronized {
      val cacheRoot = java.nio.file.Paths.get("target", "sysl_test_diag_cache",
        label + "_" + stagingCounter.incrementAndGet()).toAbsolutePath
      if Files.exists(cacheRoot) then deleteRecursive(cacheRoot)
      Files.createDirectories(cacheRoot)
      val fetcher = new JvmGitFetcher(cacheRoot.toString)
      val saved = GitFetcherProvider.instance
      GitFetcherProvider.instance = Some(fetcher)
      try body(cacheRoot, fetcher)
      finally GitFetcherProvider.instance = saved
    }

  // ---- Lock format version check ----------------------------------

  "a lock file with version newer than this sysl is rejected with a clear error" in {
    val (abs, rel) = stagingDir("lockver")
    writeFile(abs, "app/sysl.toml",
      """[package]
        |name = "lockver_app"
        |version = "0.1.0"
        |""".stripMargin)
    writeFile(abs, "app/app/main.lsysl",
      """    module app
        |    #test
        |    t() -> unit = ()
        |""".stripMargin)
    // Hand-write a future-version lock at the project root.
    writeFile(abs, "app/sysl.lock",
      """# This file is automatically @generated by sysl. Do not edit manually.
        |version = 9999
        |""".stripMargin)

    val (_, out) = runCli("test", s"$rel/app/app/main.lsysl")
    withClue(out) {
      out should include("lock file version 9999 is newer than this sysl can read")
      out should include("upgrade sysl")
    }
  }

  "a lock file with a missing version field is replaced after a warning" in {
    val (abs, rel) = stagingDir("lockver_missing")
    writeFile(abs, "app/sysl.toml",
      """[package]
        |name = "lvm_app"
        |version = "0.1.0"
        |""".stripMargin)
    writeFile(abs, "app/sysl.lock", "not_version = 1\n")

    val (_, out) = runCli("fetch", s"$rel/app")
    withClue(out) {
      out should include("warning: ignoring unparseable sysl.lock")
      out should include("missing or invalid `version` field")
    }
    // After the warning, the lock should have been overwritten with a valid one.
    val rewritten = Files.readString(abs.resolve("app/sysl.lock"))
    rewritten should include("version = 1")
  }

  // ---- --locked diagnostic ----------------------------------------

  "--locked errors when no sysl.lock exists" in {
    val (abs, rel) = stagingDir("locked_missing")
    writeFile(abs, "app/sysl.toml",
      """[package]
        |name = "lm_app"
        |version = "0.1.0"
        |""".stripMargin)
    writeFile(abs, "app/sub/sysl.toml",
      """[package]
        |name = "lm_lib"
        |version = "0.1.0"
        |""".stripMargin)
    writeFile(abs, "app/sysl.toml",
      """[package]
        |name = "lm_app"
        |version = "0.1.0"
        |
        |[dependencies]
        |lm_lib = { path = "sub" }
        |""".stripMargin)

    val (_, out) = runCli("fetch", "--locked", s"$rel/app")
    withClue(out) {
      out should include("--locked specified but sysl.lock is missing")
      out should include("run `sysl fetch` first")
    }
  }

  "--locked errors when the lock is stale" in {
    val (abs, rel) = stagingDir("locked_stale")
    writeFile(abs, "app/sysl.toml",
      """[package]
        |name = "ls_app"
        |version = "0.1.0"
        |""".stripMargin)
    writeFile(abs, "app/app/main.lsysl",
      """    module app
        |    #test
        |    t() -> unit = ()
        |""".stripMargin)
    // Write the lock first (no deps).
    val (codeOk, _) = runCli("fetch", s"$rel/app")
    withClue("initial fetch") { codeOk shouldBe 0 }
    // Now mutate the manifest to add a path dep — lock is stale.
    writeFile(abs, "app/sub/sysl.toml",
      """[package]
        |name = "ls_lib"
        |version = "0.1.0"
        |""".stripMargin)
    writeFile(abs, "app/sysl.toml",
      """[package]
        |name = "ls_app"
        |version = "0.1.0"
        |
        |[dependencies]
        |ls_lib = { path = "sub" }
        |""".stripMargin)

    val (_, out) = runCli("fetch", "--locked", s"$rel/app")
    withClue(out) {
      out should include("--locked")
      out should include("out of date")
      out should include("`sysl fetch`")
    }
  }

  "--locked succeeds and does not modify the lock when it already matches" in {
    val (abs, rel) = stagingDir("locked_ok")
    writeFile(abs, "app/sub/sysl.toml",
      """[package]
        |name = "lo_lib"
        |version = "0.1.0"
        |""".stripMargin)
    writeFile(abs, "app/sysl.toml",
      """[package]
        |name = "lo_app"
        |version = "0.1.0"
        |
        |[dependencies]
        |lo_lib = { path = "sub" }
        |""".stripMargin)
    writeFile(abs, "app/app/main.lsysl",
      """    module app
        |    #test
        |    t() -> unit = ()
        |""".stripMargin)

    runCli("fetch", s"$rel/app")
    val before = Files.readString(abs.resolve("app/sysl.lock"))
    val mtimeBefore = Files.getLastModifiedTime(abs.resolve("app/sysl.lock"))

    val (_, out) = runCli("fetch", "--locked", s"$rel/app")
    withClue(out) { out should include("up to date") }
    val after = Files.readString(abs.resolve("app/sysl.lock"))
    after shouldBe before
    Files.getLastModifiedTime(abs.resolve("app/sysl.lock")) shouldBe mtimeBefore
  }

  "--locked is rejected on the `update` subcommand" in {
    val (_, rel) = stagingDir("update_locked")
    // scopt parser-failure mode: code=2, no execute() runs. Verify that the
    // checkConfig diagnostic surfaces in the help output (scopt prints it
    // before the usage block).
    val (code, out) = runCli("update", "--locked", rel)
    withClue(out) {
      // Either scopt's parse-failure exit code or the diagnostic substring is
      // enough — this test pins the contract that the combination is refused.
      code shouldBe 2
      out.toLowerCase should include("locked")
    }
  }

  // ---- --frozen diagnostic ----------------------------------------

  "--frozen on a fresh project with a git dep refuses network IO" in
    withFetcher("frozen_unpinned") { (_, _) =>
      val (abs, rel) = stagingDir("frozen_unpinned")
      val (_, url) = libFixture(abs.resolve("repo"), "fu_lib", "0.1.0", 3)
      writeFile(abs, "app/sysl.toml",
        s"""[package]
           |name = "fu_app"
           |version = "0.1.0"
           |
           |[dependencies]
           |fu_lib = { git = "$url", branch = "main" }
           |""".stripMargin)
      writeFile(abs, "app/app/main.lsysl",
        """    module app
          |    #test
          |    t() -> unit = ()
          |""".stripMargin)

      val (_, out) = runCli("fetch", "--frozen", s"$rel/app")
      withClue(out) {
        out should include("offline mode (--frozen)")
        out should include("not pinned by sysl.lock")
      }
    }

  "--frozen succeeds when every git dep is already pinned and cached" in
    withFetcher("frozen_ok") { (_, _) =>
      val (abs, rel) = stagingDir("frozen_ok")
      val (sha, url) = libFixture(abs.resolve("repo"), "fok_lib", "0.1.0", 5)
      writeFile(abs, "app/sysl.toml",
        s"""[package]
           |name = "fok_app"
           |version = "0.1.0"
           |
           |[dependencies]
           |fok_lib = { git = "$url", branch = "main" }
           |""".stripMargin)
      writeFile(abs, "app/app/main.lsysl",
        """    module app
          |    #test
          |    t() -> unit = ()
          |""".stripMargin)

      val (codeFetch, _) = runCli("fetch", s"$rel/app")
      withClue("warm fetch") { codeFetch shouldBe 0 }
      val (_, out) = runCli("fetch", "--frozen", s"$rel/app")
      withClue(out) {
        out should include("up to date")
      }
      val lock = Files.readString(abs.resolve("app/sysl.lock"))
      lock should include(sha)
    }

  // ---- Conflict context -------------------------------------------

  "git conflict error names both consuming manifests and their declared refs" in
    withFetcher("conflict_ctx") { (_, _) =>
      val (abs, rel) = stagingDir("conflict_ctx")
      val repoDir = abs.resolve("repo")
      val (firstSha, url) = libFixture(repoDir, "shared", "1.0.0", 1)
      writeFile(repoDir, "lib/extra.lsysl",
        """    module lib
          |    extra() -> int = 2
          |""".stripMargin)
      git(repoDir, "add", "lib/extra.lsysl")
      git(repoDir, "commit", "--quiet", "-m", "second")
      val secondSha = git(repoDir, "rev-parse", "HEAD")

      writeFile(abs, "ws/sysl.toml",
        """[workspace]
          |members = ["a", "b"]
          |""".stripMargin)
      writeFile(abs, "ws/a/sysl.toml",
        s"""[package]
           |name = "a_app"
           |version = "0.1.0"
           |
           |[dependencies]
           |first = { git = "$url", rev = "$firstSha" }
           |""".stripMargin)
      writeFile(abs, "ws/a/a/main.lsysl",
        """    module a
          |    #test
          |    t() -> unit = ()
          |""".stripMargin)
      writeFile(abs, "ws/b/sysl.toml",
        s"""[package]
           |name = "b_app"
           |version = "0.1.0"
           |
           |[dependencies]
           |second = { git = "$url", rev = "$secondSha" }
           |""".stripMargin)
      writeFile(abs, "ws/b/b/main.lsysl",
        """    module b
          |    #test
          |    t() -> unit = ()
          |""".stripMargin)

      val (_, out) = runCli("fetch", s"$rel/ws")
      withClue(out) {
        out should include("conflicting git refs")
        out should include(url)
        // both consumer manifests cited
        out should include("ws/a/sysl.toml")
        out should include("ws/b/sysl.toml")
        // both aliases cited
        out should include("`first`")
        out should include("`second`")
        // both shas cited (truncated to 7 chars per the formatter)
        out should include(firstSha.take(7))
        out should include(secondSha.take(7))
      }
    }

  // ---- sysl tree --------------------------------------------------

  "sysl tree prints a single-package project with a path dep" in {
    val (abs, rel) = stagingDir("tree_simple")
    writeFile(abs, "app/sub/sysl.toml",
      """[package]
        |name = "ts_lib"
        |version = "0.4.0"
        |""".stripMargin)
    writeFile(abs, "app/sysl.toml",
      """[package]
        |name = "ts_app"
        |version = "0.2.0"
        |
        |[dependencies]
        |ts_lib = { path = "sub" }
        |""".stripMargin)

    val (_, out) = runCli("tree", s"$rel/app")
    withClue(out) {
      out should include("ts_app v0.2.0 (local)")
      out should include("└── ts_lib v0.4.0")
    }
  }

  "sysl tree prints one tree per workspace member" in {
    val (abs, rel) = stagingDir("tree_ws")
    writeFile(abs, "ws/sysl.toml",
      """[workspace]
        |members = ["a", "b"]
        |""".stripMargin)
    writeFile(abs, "ws/a/sysl.toml",
      """[package]
        |name = "tw_a"
        |version = "0.1.0"
        |""".stripMargin)
    writeFile(abs, "ws/b/sysl.toml",
      """[package]
        |name = "tw_b"
        |version = "0.1.0"
        |""".stripMargin)

    val (_, out) = runCli("tree", s"$rel/ws")
    withClue(out) {
      out should include("tw_a v0.1.0 (local)")
      out should include("tw_b v0.1.0 (local)")
    }
  }

  "sysl tree prints git deps with their resolved sha" in
    withFetcher("tree_git") { (_, _) =>
      val (abs, rel) = stagingDir("tree_git")
      val (sha, url) = libFixture(abs.resolve("repo"), "tg_lib", "0.1.0", 1)
      writeFile(abs, "app/sysl.toml",
        s"""[package]
           |name = "tg_app"
           |version = "0.1.0"
           |
           |[dependencies]
           |tg_lib = { git = "$url", branch = "main" }
           |""".stripMargin)
      writeFile(abs, "app/app/main.lsysl",
        """    module app
          |    #test
          |    t() -> unit = ()
          |""".stripMargin)

      val (_, out) = runCli("tree", s"$rel/app")
      withClue(out) {
        out should include("tg_app v0.1.0 (local)")
        out should include(s"└── tg_lib v0.1.0 (git+$url#${sha.take(7)})")
      }
    }
}
