#!/bin/bash
# Cross-compile busybox against the SLIX musl fork, producing a
# dynamically-linked PIE ELF at /tmp/slix-<arch>/bin/busybox.
#
# Usage:
#   ./build-busybox.sh                    # default --arch=aarch64
#   ./build-busybox.sh --arch=x86_64
#   ./build-busybox.sh --clean            # wipe the per-arch build tree
#
# Prereqs:
#   * slix/build-musl[-x86]/lib/libc.so + crt{i,n,1,Scrt1}.o
#     (run slix/build-musl[-x86].sh first)
#   * slix/busybox/ — pristine busybox source tree (gitignored).
#     This script will download + extract busybox 1.37.0 if missing.
#   * Homebrew clang + lld + llvm-ar / llvm-strip (chunk-9 toolchain).
#
# Output:
#   /tmp/slix-<arch>/bin/busybox  (PIE dynamic ELF, PT_INTERP /lib/ld-musl-<arch>.so.1)
#
# Build tree lives at slix/build-busybox[-x86]/  (gitignored).
# .config is generated by merging slix/busybox-config/slix.config onto
# busybox's defconfig — that file is the *only* committed config artifact.

set -e

BUSYBOX_VERSION=1.37.0
BUSYBOX_URL="https://busybox.net/downloads/busybox-${BUSYBOX_VERSION}.tar.bz2"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SRC_DIR="$REPO_ROOT/slix/busybox"

ARCH=aarch64
CLEAN=0
for arg in "$@"; do
    case "$arg" in
        --arch=aarch64) ARCH=aarch64 ;;
        --arch=x86_64)  ARCH=x86_64 ;;
        --arch=*)       echo "Unknown --arch: $arg" >&2; exit 2 ;;
        --clean)        CLEAN=1 ;;
        *)              echo "Unknown arg: $arg" >&2; exit 2 ;;
    esac
done

case "$ARCH" in
    aarch64)
        BUILD_DIR="$REPO_ROOT/slix/build-busybox"
        OUT_DIR=/tmp/slix-aarch64
        MUSL_BUILD="$REPO_ROOT/slix/build-musl"
        MUSL_ARCH_INC="$REPO_ROOT/slix/musl/arch/aarch64-slix"
        CLANG_TARGET=aarch64-slix-linux-musl
        DYNAMIC_LINKER=/lib/ld-musl-aarch64.so.1
        BB_ARCH=arm64
        ;;
    x86_64)
        BUILD_DIR="$REPO_ROOT/slix/build-busybox-x86"
        OUT_DIR=/tmp/slix-x86_64
        MUSL_BUILD="$REPO_ROOT/slix/build-musl-x86"
        MUSL_ARCH_INC="$REPO_ROOT/slix/musl/arch/x86_64-slix"
        CLANG_TARGET=x86_64-slix-linux-musl
        DYNAMIC_LINKER=/lib/ld-musl-x86_64.so.1
        BB_ARCH=x86_64
        ;;
esac

CLANG=/opt/homebrew/opt/llvm/bin/clang
LD=/opt/homebrew/opt/lld/bin/ld.lld
AR=/opt/homebrew/opt/llvm/bin/llvm-ar
STRIP=/opt/homebrew/opt/llvm/bin/llvm-strip
HOSTCC=/usr/bin/clang   # builds kbuild helpers (mkapplet, etc.) — runs natively

for tool in "$CLANG" "$LD" "$AR" "$STRIP" "$HOSTCC"; do
    if [ ! -x "$tool" ]; then
        echo "Missing tool: $tool" >&2
        echo "Install with: brew install llvm lld" >&2
        exit 1
    fi
done

if [ ! -f "$MUSL_BUILD/lib/libc.so" ]; then
    echo "Missing $MUSL_BUILD/lib/libc.so" >&2
    echo "Run slix/build-musl${ARCH:+${ARCH/aarch64/}}${ARCH:+${ARCH/x86_64/-x86}}.sh first." >&2
    exit 1
fi

# === Fetch busybox source if missing =====================================
if [ ! -f "$SRC_DIR/Makefile" ]; then
    echo "=== Fetching busybox ${BUSYBOX_VERSION} source ==="
    mkdir -p "$(dirname "$SRC_DIR")"
    TARBALL="/tmp/busybox-${BUSYBOX_VERSION}.tar.bz2"
    if [ ! -f "$TARBALL" ]; then
        curl -fsSL "$BUSYBOX_URL" -o "$TARBALL"
    fi
    rm -rf "$SRC_DIR"
    tar -xjf "$TARBALL" -C "$(dirname "$SRC_DIR")"
    mv "$(dirname "$SRC_DIR")/busybox-${BUSYBOX_VERSION}" "$SRC_DIR"
fi

if [ "$CLEAN" = "1" ]; then
    echo "=== Cleaning $BUILD_DIR ==="
    rm -rf "$BUILD_DIR"
fi

mkdir -p "$BUILD_DIR"

# === Construct CC wrapper ================================================
# busybox kbuild uses `$(CC)` directly with positional args. We need clang
# to always get the right --target + isystem set + -B for crt discovery;
# rather than fight kbuild we generate a small wrapper shim per arch.
#
# -B$MUSL_BUILD/lib lets clang's driver find Scrt1.o / crti.o / crtn.o
# automatically when linking a PIE — saves us from listing them on the
# command line and avoids the "Scrt1.o in EXTRA_LDFLAGS leaks to ld -r"
# problem (which is why CONFIG_PIE=y handles -pie itself).
CC_WRAPPER="$BUILD_DIR/cc-wrapper.sh"
cat > "$CC_WRAPPER" <<EOF
#!/bin/bash
# cc-wrapper.sh — clang shim used as \$(CC) by busybox kbuild.
#
# For compiles and intermediate links the wrapper passes through with
# only the cross-compile setup. For the BUSYBOX FINAL LINK (detected
# by the output name "busybox_unstripped") it adds -nostdlib plus the
# musl-flavored crt + libc, and -fuse-ld=lld so clang's driver doesn't
# fall back to the macOS host ld. This avoids leaking ld.lld / Scrt1.o
# / -dynamic-linker into the intermediate \`ld -r\` calls that build
# per-directory built-in.o.

set -e

ARGS=("\$@")

is_final_link=0
for ((i=0; i<\${#ARGS[@]}; i++)); do
    if [ "\${ARGS[\$i]}" = "-o" ] && [ "\${ARGS[\$((i+1))]}" = "busybox_unstripped" ]; then
        is_final_link=1
        break
    fi
done

COMMON_FLAGS=(
    --target=$CLANG_TARGET
    -ffreestanding
    -fno-stack-protector
    -nostdinc
    -isystem "$MUSL_ARCH_INC"
    -isystem "$MUSL_BUILD/obj/include"
    -isystem "$REPO_ROOT/slix/musl/arch/generic"
    -isystem "$REPO_ROOT/slix/musl/include"
)

if [ \$is_final_link -eq 1 ]; then
    # PIE dynamic link against musl. We use -nostdlib (skip all driver-
    # added crts AND default libs), then explicitly pass Scrt1.o + crti.o
    # before the user objects and crtn.o + libc.so after. -L points at
    # our musl build so the busybox-auto-injected -lm resolves to our
    # libm.a stub. ld.lld is invoked directly through --ld-path to keep
    # clang from probing for the host linker.
    exec "$CLANG" \\
        "\${COMMON_FLAGS[@]}" \\
        -fuse-ld=lld \\
        --ld-path="$LD" \\
        -nostdlib \\
        -pie \\
        -Wl,-dynamic-linker,"$DYNAMIC_LINKER" \\
        -Wl,-z,max-page-size=0x1000 \\
        -Wl,--allow-shlib-undefined \\
        -L"$MUSL_BUILD/lib" \\
        "$MUSL_BUILD/lib/Scrt1.o" \\
        "$MUSL_BUILD/lib/crti.o" \\
        "\${ARGS[@]}" \\
        "$MUSL_BUILD/lib/libc.so" \\
        "$MUSL_BUILD/lib/crtn.o"
else
    exec "$CLANG" "\${COMMON_FLAGS[@]}" "\$@"
fi
EOF
chmod +x "$CC_WRAPPER"

# === Generate the .config ================================================
# Start from defconfig (everything enabled), then overlay our trim layer
# from slix/busybox-config/slix.config. The trim file *replaces* values
# rather than appending — kbuild handles the merge via `make olddefconfig`
# after we cat it on top.
CONFIG_TRIM="$REPO_ROOT/slix/busybox-config/slix.config"

cd "$SRC_DIR"

if [ ! -f "$BUILD_DIR/.config" ]; then
    echo "=== Generating .config (allnoconfig + slix overlay) ==="
    make O="$BUILD_DIR" allnoconfig HOSTCC="$HOSTCC"
    if [ -f "$CONFIG_TRIM" ]; then
        # busybox 1.37 kconfig has neither `olddefconfig` nor a
        # silent fragment merge. APPENDING our overlay does not work
        # — kconfig reads the first occurrence of each symbol and
        # warns "trying to reassign symbol X" on the duplicate,
        # silently dropping the override. Patch the .config in place
        # instead: for each CONFIG_X=y in the overlay, flip the
        # corresponding `# CONFIG_X is not set` line. Pure-bash, no
        # sed (CLAUDE.md rule).
        python3 - "$CONFIG_TRIM" "$BUILD_DIR/.config" <<'PY'
import re, sys
overlay_path, config_path = sys.argv[1], sys.argv[2]
overrides = {}
for raw in open(overlay_path):
    line = raw.rstrip('\n')
    s = line.strip()
    if not s or s.startswith('#'):
        continue
    m = re.match(r'(CONFIG_[A-Z0-9_]+)=(.*)$', s)
    if m:
        overrides[m.group(1)] = line
config_lines = open(config_path).read().splitlines()
seen = set()
out = []
for ln in config_lines:
    matched = False
    m = re.match(r'# (CONFIG_[A-Z0-9_]+) is not set', ln)
    if m and m.group(1) in overrides:
        out.append(overrides[m.group(1)])
        seen.add(m.group(1))
        matched = True
        continue
    m = re.match(r'(CONFIG_[A-Z0-9_]+)=', ln)
    if m and m.group(1) in overrides:
        out.append(overrides[m.group(1)])
        seen.add(m.group(1))
        matched = True
        continue
    out.append(ln)
# Append any overrides that didn't match an existing line (new symbols).
for name, line in overrides.items():
    if name not in seen:
        out.append(line)
open(config_path, 'w').write('\n'.join(out) + '\n')
print(f'merged {len(overrides)} overrides into .config ({len(seen)} matched existing lines)')
PY
        # `yes "" | oldconfig` resolves any dependencies pulled in by
        # the overlay (e.g. enabling CONFIG_CAT may auto-enable some
        # FEATURE_* options). Accepts kconfig defaults for every new
        # symbol — including choice-block selections — without going
        # interactive.
        yes "" | make O="$BUILD_DIR" oldconfig HOSTCC="$HOSTCC" > "$BUILD_DIR/oldconfig.log" 2>&1
    fi
fi

# === Build ===============================================================
# Pass our cross toolchain via env. KBUILD_VERBOSE=1 dumps every command;
# leave it on for the initial port so failures are easy to diagnose.
#
# CFLAGS_busybox carries link-only flags (busybox's Makefile passes
# CFLAGS+CFLAGS_busybox to the final-link `$(CC)` invocation only — see
# cmd_busybox__ at busybox/Makefile:609). Putting -Wl,... here is the
# right place: clang treats them as link options, and they never reach
# the intermediate `ld -r` calls that build per-directory built-in.o.
#
# EXTRA_LDFLAGS stays empty for the same reason. CONFIG_PIE=y in
# slix.config takes care of -pie (CFLAGS_busybox) and -fpie (CFLAGS).
echo "=== Building busybox ($ARCH) ==="
make -C "$SRC_DIR" O="$BUILD_DIR" \
    ARCH="$BB_ARCH" \
    HOSTCC="$HOSTCC" \
    CC="$CC_WRAPPER" \
    LD="$LD" \
    AR="$AR" \
    STRIP="$STRIP" \
    SKIP_STRIP=y \
    KBUILD_VERBOSE=1 \
    -j"$(sysctl -n hw.ncpu)" \
    busybox

mkdir -p "$OUT_DIR/bin"
cp "$BUILD_DIR/busybox_unstripped" "$OUT_DIR/bin/busybox"
chmod +x "$OUT_DIR/bin/busybox"

echo "=== Built: $OUT_DIR/bin/busybox ($(wc -c < "$OUT_DIR/bin/busybox" | tr -d ' ') bytes) ==="
